PKGDIR ?= ..
L4DIR  ?= $(PKGDIR)/../../..

PKGNAME         = libgcc_eh
CONTRIB_HEADERS = y
INCSRC_DIR      = $(OBJ_DIR)/../include-gen/src

include $(PKGDIR)/headers.inc

TARGET          = $(UNWIND_HEADERS)

include $(L4DIR)/mk/include.mk
